---
kind: pipeline
type: docker
name: default

steps:
  - name: source
    image: alpine:3.11
    commands:
      - apk add --update --no-cache curl git jq
      - LATEST=$(curl -s https://api.github.com/repos/docker/buildx/releases/latest | jq -r ".tag_name")
      - if curl -sfL https://hub.docker.com/v2/repositories/ezkrg/buildx/tags/$LATEST > /dev/null; then echo "tag $LATEST already exist"; exit 78; fi
      - curl -sL --output buildx https://github.com/docker/buildx/releases/download/$LATEST/buildx-$LATEST.linux-amd64
      - chmod a+x buildx
      - echo -n "$LATEST,latest" > .tags

  - name: release
    image: plugins/docker
    settings:
      username:
        from_secret: DHU
      password:
        from_secret: DHP
      repo: ezkrg/buildx
      when:
        event:
          - cron
        cron:
          - nightly
---
kind: signature
hmac: ae9bf46f59529624480e174f92f7fc2b0330d0442016d7be767489be5699902f

...
